version: "3"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
  node:
    build: ./node
    depends_on:
      - redis
    environment:
      REDIS: redis
    ports:
      - "8080:8080"
